logdata:
  extends:
    file: ../docker-compose-commons.yml
    service: logdata
   
entry:
  extends:
    file: ../docker-compose-commons.yml
    service: entry
  volumes:
    - ./boot-scripts/03-virtuoso-backend.js:/etc/fusepool-p3/boot-scripts/03-virtuoso-backend.js
   
vos:
  image: openlink/virtuoso_opensource:vos
  ports:
    - "1111:1111"
    - "8890:8890"
  volumes:
    - /opt/virtuoso-opensource/var/lib/virtuoso/db:/opt/virtuoso-opensource/var/lib/virtuoso/db

core:
  extends:
    file: ../docker-compose-commons.yml
    service: core
  links:
    - elk
    - vos:ldp
  volumes_from:
    - logdata
  environment:
    - LDPURI=http://ldp:8890/
    
stanbol:
  extends:
    file: ../docker-compose-commons.yml
    service: stanbol
   
batchrefine:
  extends:
    file: ../docker-compose-commons.yml
    service: batchrefine
  volumes_from:
    - logdata
    
openrefine:
  extends:
    file: ../docker-compose-commons.yml
    service: openrefine
  volumes_from:
    - logdata
    
elk:
  extends:
    file: ../docker-compose-commons.yml
    service: elk

pundittransformer:
  extends:
    file: ../docker-compose-commons.yml
    service: pundittransformer
  links:
    - core
    - vos:ldp
    - entry