logdata:
  image: busybox
  volumes:
   - /var/log
  restart: always
core:
  image: fusepoolp3/platform-reference-implementat
  ports:
   - "80:80"
   - "8181:8181"
   - "8151:8151"
   - "8200:8200"
   - "8201:8201"
   - "8202:8202"
   - "8203:8203"
   - "8204:8204"
   - "8205:8205"
   - "8300:8300"
   - "8301:8301"
   - "8302:8302"
   - "8303:8303"
   - "8304:8304"
   - "8305:8305"
   - "8306:8306"
   - "8307:8307"
   - "8308:8308"
   - "8388:8388"
  volumes:
    - ./core/ELK/logstash-config/patterns:/etc/logstash-config/patterns/
    - ./core/ELK/logstash-ssl:/etc/ssl/
    - ./core/ELK/logstash-forwarder.conf:/etc/logstash-forwarder.conf
  volumes_from:
    - logdata
  links:
   - elk
  restart: always
batchrefine:
  image: fusepool/p3-batchrefine
  ports:
   - "8310:8310"
  volumes_from:
   - logdata
  restart: always
openrefine:
  image: fusepool/openrefine
  ports:
    - "8389:3333"
  volumes_from:
   - logdata
  restart: always
elk:
  image: willdurand/elk
  ports:
    - "9200:9200"
    - "8387:80"
    - "127.0.0.1:5043:5043"
#    - 5043:5043"
  volumes:
    - ./core/ELK/logstash-ssl:/etc/ssl
    - ./core/ELK/logstash-config:/etc/logstash
#  links:
#   - core
  restart: always


pundittransformer:
  image: danilogiacomi/pundit
  ports:
   - "8386:80"
  restart: always

#environment:
#   - IR_URL=`/sbin/ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'` 
